### ISSUE TITLE
[Feature Request] A type safe way to build a URL in Nim mode

### ISSUE THREAD

**Issue by ajusa** [dizzyliam/pigeon#3]
I'm trying out pigeon for use in some server side rendered pages, as I think the autoRoute functionality is very cool and useful.

Since I'm not using the JS mode, it'd be nice if I could somehow call a proc and get the string which would correspond to the path I would need to make a POST request to, or any other kind of request. It's a bit difficult to explain, so here's what I'd expect it to look like:

```nim
autoRoute:
  proc getInfo(id: int): string = "some info"
  proc deleteInfo(id: int): string = "some info"
  POST "/posts/{id}"
  proc updateInfo(id: int, info: string): string = "some info"

buildGetInfo(4) == "/getInfo?id=4"
buildDeleteInfo(4) == "/getInfo?id=4"
buildUpdateInfo(4) == "/posts/4"
```

I believe this should be *possible*.  It would be a really nice feature for those that are using server side rendering, or want to build a Nim client for their webapp!
  
```

**Comment by dizzyliam** [comment]
Thanks for the feature request. A near-future goal is to be able to generate API documentation, so that you can more easily use a pigeon server without using pigeon on the frontend. Would that fulfill the same need? I don't see much use in generating those paths in code.

**Comment by ajusa** [comment]
Yes, I think that would be sufficient (and really cool!). Thanks!
