### ISSUE TITLE
Support form data

### ISSUE THREAD

**Issue by dizzyliam** [dizzyliam/pigeon#5]
Currently POST routes expect a JSON body only, because that's what the generated frontend procs use to encapsulate arguments. However, it would be nice if these endpoints could also be submitted to by forms for clients not using pigeon.

Should be simple to implement, just check for `multipart/form-data` and parse that instead. I'll work on this soon :)

**Comment by dizzyliam** [comment]
@ajusa Done. `nimble install pigeon@#head` to try it out. I'll include it in the next release as well.

**Comment by ajusa** [comment]
Just tried it out, this works great! Would it also be possible to include `application/x-www-form-urlencoded`? Seems like it wouldn't be too hard based on the commit I saw for this.

**Comment by dizzyliam** [comment]
`application/x-www-form-urlencoded` is supported in v0.3.0
