### ISSUE TITLE
Access the Prologue context more easily 

### ISSUE THREAD

**Issue by ajusa** [dizzyliam/pigeon#6]
I know that there is a way to pass a specific route directly to prologue, but it would be pretty useful to access the context in other routes as well.

My specific use case is reading information stored in a cookie (auth) on nearly every request.

**Comment by dizzyliam** [comment]
Sorry for the wait. This would probably require a bit of refactoring, but it's a good idea, so I'll look into it.

**Comment by dizzyliam** [comment]
This is included in the v0.3.0 release. Check the 'Prologue Context' section of the README.
